#!/usr/bin/env nu

const SELF = path self
let script_path = $SELF
| path relative-to $env.PWD

let version = (version).version;

help commands
| where $it.command_type == built-in
| each { get name | split row " " | get 0 }
| uniq
| to json
| $'// Generated by `($script_path)` with nushell ($version)
export default ($in)'
| save --force src/builtins.ts
