name: build_and_deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      # Workaround for the fact that bun seems to use nondeterminstic install
      # order / script order, sometimes resulting in missing tree-sitter binary
      - run: bun install -g tree-sitter-cli

      - run: bun ci --workspaces
      - run: bun dist

      - name: Upload pages archive
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: packages/demo/public/

      - name: Deploy to pages
        uses: actions/deploy-pages@v4.0.5
